version: "3.9"
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=e_wallet_app_v1
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123456789@postgres:5432/e_wallet_app_v1?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
