// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalanceByAccountNumber(ctx context.Context, arg AddAccountBalanceByAccountNumberParams) (Account, error)
	AddAccountBalanceByID(ctx context.Context, arg AddAccountBalanceByIDParams) (Account, error)
	CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetAccountByAccountNumber(ctx context.Context, accountNumber string) (Account, error)
	GetAccountByID(ctx context.Context, id int64) (Account, error)
	GetAccountByIDForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
