// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: service_e_wallet_app.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EWalletAppClient is the client API for EWalletApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EWalletAppClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type eWalletAppClient struct {
	cc grpc.ClientConnInterface
}

func NewEWalletAppClient(cc grpc.ClientConnInterface) EWalletAppClient {
	return &eWalletAppClient{cc}
}

func (c *eWalletAppClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/protogen.EWalletApp/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eWalletAppClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/protogen.EWalletApp/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EWalletAppServer is the server API for EWalletApp service.
// All implementations must embed UnimplementedEWalletAppServer
// for forward compatibility
type EWalletAppServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedEWalletAppServer()
}

// UnimplementedEWalletAppServer must be embedded to have forward compatible implementations.
type UnimplementedEWalletAppServer struct {
}

func (UnimplementedEWalletAppServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedEWalletAppServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedEWalletAppServer) mustEmbedUnimplementedEWalletAppServer() {}

// UnsafeEWalletAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EWalletAppServer will
// result in compilation errors.
type UnsafeEWalletAppServer interface {
	mustEmbedUnimplementedEWalletAppServer()
}

func RegisterEWalletAppServer(s grpc.ServiceRegistrar, srv EWalletAppServer) {
	s.RegisterService(&EWalletApp_ServiceDesc, srv)
}

func _EWalletApp_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EWalletAppServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protogen.EWalletApp/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EWalletAppServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EWalletApp_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EWalletAppServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protogen.EWalletApp/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EWalletAppServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EWalletApp_ServiceDesc is the grpc.ServiceDesc for EWalletApp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EWalletApp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protogen.EWalletApp",
	HandlerType: (*EWalletAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _EWalletApp_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _EWalletApp_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_e_wallet_app.proto",
}
